// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX-ErtJ-YzGrsmA35-QVowcIGEcyIRPjs',
    appId: '1:686452527533:web:96e80f3e108d8f3015d124',
    messagingSenderId: '686452527533',
    projectId: 'rakta-bandhan2026',
    authDomain: 'rakta-bandhan2026.firebaseapp.com',
    storageBucket: 'rakta-bandhan2026.firebasestorage.app',
    measurementId: 'G-D7RXE48E0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1pAyg9LQwU94Qli0R1BubgDsMBA6n9CA',
    appId: '1:686452527533:android:1612485ff7a2ebc715d124',
    messagingSenderId: '686452527533',
    projectId: 'rakta-bandhan2026',
    storageBucket: 'rakta-bandhan2026.firebasestorage.app',
  );
}
